disabled_rules:
  - opening_brace
included:
  - Source
  - Tests
excluded:
  - Carthage
opt_in_rules:
  - empty_count
variable_name:
  min_length:
    warning: 0
  max_length:
    warning: 60
line_length:
  warning: 160
  error: 160
