language: objective-c
osx_image: xcode8
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
install:
  - gem install xcpretty
before_script:
  - rake carthage:build
script:
  - rake test:ios
